### ISSUE TITLE
Android platform runs slowly

### ISSUE THREAD

**Issue by LLSean** [AnetaTexler/FaceBlit#11]
Android platform runs slowly, FPS 0.3.Any solutions for speeding predict?

**Comment by AnetaTexler** [comment]
Hi!
Did you build it as release?

![Screenshot 2021-05-26 095748](https://user-images.githubusercontent.com/17759542/121429696-7d92dc80-c977-11eb-96b7-4f3cf38b8044.png)

**Comment by LLSean** [comment]
I'm sorry to response slowly.I'll try it, thanks

**Comment by watertianyi** [comment]
@LLSean Flashback on android
