### ISSUE TITLE
How to set the compiling configuration in VS2019 to increase speed?

### ISSUE THREAD

**Issue by sd707589** [AnetaTexler/FaceBlit#13]
Hi @AnetaTexler, 
Thank you for sharing this brilliant project. I am facing a time-cost issue needing your help.
I saw the paper said that the synthesis costs about 0.05 s. But when I compile the C++ project in VS2019, the synthesis time is much longer as below:
- Landmarks detection time: 180 ms
- Style transfer time: 111 ms.

I have already changed the project in 'release' mode.
In the code, NNF_patchsize=3; frame_size=768x1024.
I guess there may be some configurations different from the paper. Please help.

Thank you!

**Comment by AnetaTexler** [comment]
Hi!
I apologize for the late reply and thank you for your interest in our project!
In our paper, the measuring was done on a slightly smaller image (0.5 megapixel) and without voting which is not necessary (it only improves the quality a bit). So, try to set the NNF_patchsize=0 to turn off the voting. Please, let me know if it helped.
