### ISSUE TITLE
Problems with building the codes

### ISSUE THREAD

**Issue by bycloudai** [AnetaTexler/FaceBlit#2]
Hi, the work you guys have on here looks amazing!

I was trying to build it on my machine, but I've encountered this error:

![image](https://user-images.githubusercontent.com/29135514/115948871-54230c00-a503-11eb-96d3-d5f15d09ef5b.png)

How can I fix this?

Thanks in advance!

**Comment by cvtuge** [comment]
> Hi, the work you guys have on here looks amazing!
> 
> I was trying to build it on my machine, but I've encountered this error:
> 
> ![image](https://user-images.githubusercontent.com/29135514/115948871-54230c00-a503-11eb-96d3-d5f15d09ef5b.png)
> 
> How can I fix this?
> 
> Thanks in advance!

I have the same problem, do you fix this?

**Comment by AnetaTexler** [comment]
Hi guys! 

Thank you for your interest! 

Sorry for the issue! Please, pull the last changes, I fixed the problem. Hope it helps!

I'll close the issue, please, let me know if there are any other problems. Good luck!

**Comment by bycloudai** [comment]
Hi, sorry to bother you again.
I ran into this error:
![image](https://user-images.githubusercontent.com/29135514/116180343-5677a700-a74b-11eb-8bce-2c7a4b8056d7.png)
When I try to run main.cpp

Just to double check, what are the exact steps needed to run the "codes" as mentioned in the documentation?
Thank you!

**Comment by AnetaTexler** [comment]
Hi!
I was able to reproduce the error when I set the wrong "targetPath". So try to check that and let me know. Hope it helps!

**Comment by bycloudai** [comment]
Thanks! Everything works now.
