### ISSUE TITLE
Android app crash when I tap a style image

### ISSUE THREAD

**Issue by j52y** [AnetaTexler/FaceBlit#4]
Thank you for sharing your project. 

After successfully built with (Android Studio 4.1.3,  Gradle 6.5, **NDK 21.1.6**, arm64-v8a), the app crashes throwing error logs below when I tap a style image. Tested with PIXEL 3 XL, Galaxy Note10 5G

Abort message: 'terminating with uncaught exception of type dlib::serialization_error: Unable to open /storage/emulated/0/Download/models/shape_predictor_68_face_landmarks.dat for reading.'

[04-27 22:27:09.710  1008  1008 I EaselThermalMonit.txt](https://github.com/AnetaTexler/FaceBlit/files/6384917/04-27.22.27.09.710.1008.1008.I.EaselThermalMonit.txt)

adb shell
crosshatch:/ $ cd /storage/emulated/0/Download/models
/system/bin/sh: cd: /storage/emulated/0/Download/models: No such file or directory

There was no model directory inside Download. I also check all permissions including storage are granted.

Could anyone help me figure this out?

**Comment by AnetaTexler** [comment]
Hi!

Thank you for reporting the issue. I am so sorry, I forgot to mention in README that you need to create directory "models" inside the Download directory of your mobile storage and copy there the dlib model "shape_predictor_68_face_landmarks.dat" from "FaceBlit/VS/facemark_models".

Let me know in case there are other problems.

**Comment by j52y** [comment]
Problem solved. it works well now! I appreciate your help :)
