### ISSUE TITLE
How to generate custom landmarks and lookup tables for custom styles?

### ISSUE THREAD

**Issue by bycloudai** [AnetaTexler/FaceBlit#7]
Hi,
Is it possible to use custom style images? I presume that we need to generate custom landmarks and lookup tables if we want custom images right?

thank you!

**Comment by AnetaTexler** [comment]
Hi!
Apologies for the late reply. 
I created function `addNewStyle()` in `main.cpp` that does the thing. Please, read section "Adding a new style" in README.
Let me know if there are some issues. Hope it is useful!

**Comment by bycloudai** [comment]
Hi again!
Thank you so much for your update. It works amazingly!
But there's a small trouble that I'm encountering where editing landmarks would eat up all my computing power, and I cannot make adjustments to the landmarks GUI.

Is there a way to run it without an immense lag so I can edit the landmarks easily? Thank you!

**Comment by AnetaTexler** [comment]
Hi!
Sorry, it is not an interactive landmark editing window. It only shows you the result of detection to see if landmarks need to be edited, and after the pressing any key, the program continues.

How I do it: I save this image with drawn landmarks (`cv::imwrite(...)`), I open it in MS Paint where I can see coordinates of my cursor and I manually edit the TXT file with landmark points. I know, it is not the best solution...

However, thank you for your feedback, I will edit the function to save the image, not show it in the window, I guess it is confusing. Also, the interactive landmark editing window is a great idea, maybe, I will implement it :-)

**Comment by bycloudai** [comment]
Ok! That seems to work pretty well. 

Thanks!
