### ISSUE TITLE
How to reach 16FPS as your video demonstrated

### ISSUE THREAD

**Issue by Chalet37** [AnetaTexler/FaceBlit#8]
I tried on several mobile phone include Samsung Galaxy S9 with Exynos 9810 and Huawei with Kirin 990. I'v never found the app reach even more than 1 FPS.

I was wondering if there is anything I can do with the Android code to reach the 16 FPS?
thanks

**Comment by AnetaTexler** [comment]
Hi!
Did you build it as release?

**Comment by AnetaTexler** [comment]
![Screenshot 2021-05-26 095748](https://user-images.githubusercontent.com/17759542/119701222-67076400-be54-11eb-9aae-0438457cc4c4.png)

**Comment by Chalet37** [comment]
> Hi!
> Did you build it as release?

It works after I built it as release. Thanks
