### ISSUE TITLE
Adding style takes much longer after the second update of the code

### ISSUE THREAD

**Issue by bycloudai** [AnetaTexler/FaceBlit#9]
Hi, sorry to trouble you again!

I've just tested the newest codes (5 days ago) and adding one style takes significantly longer (5 mins vs 40 mins+) than the code 11 days ago. I noticed the change when I was trying to create a tutorial on how to run this with the latest code for my viewers.

Is it because the increase in landmarks accuracy? Or is it something else affecting in the background?
I also noticed a slightly longer runtime for running the main() module too. I'm guessing it might be related?

Thank you in advance!

**Comment by AnetaTexler** [comment]
Hi!
The changes I made should not have any effect on the speed. Are you sure you built it as release?

P.S. Thank you for your nice youtube video!
